apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-sampleapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifest/sampleapp/overlays/dev
    repoURL: https://github.com/amaya382/gitops-manifest
    targetRevision: dev
